### ISSUE TITLE
dev and prod environments

### ISSUE THREAD

**Issue by shalunov** [clostra/newnode#13]
Separate environments so the keys can be different in dev and in prod. Prod keys obviously should not be in the repo.

**Comment by shalunov** [comment]
Before writing any code, let's first discuss the proposed architecture. It's possible that this is a no-code ticket where we specify the private key file from the command-line in production or something to that effect.

**Comment by inetic** [comment]
I like the command line idea. If the command line argument isn't used, then hardcoded debug keys are be used and the user is notified on the std output.

**Comment by shalunov** [comment]
That's not the entire architecture. The client needs to know which public key to use. Also, we need to decide how to differentiate between production and development injectors and proxies if they're in the same swarm.

Feel free to propose something, or assign to me to specify.

**Comment by inetic** [comment]
> Also, we need to decide how to differentiate between production and development injectors and proxies if they're in the same swarm.

I'd go with the approach that we don't mix production and development injectors in one swarm (same for proxies). That is, instead of injectors registering in `DHT(SHA1("injectors"))` they would register in `DHT(SHA1("injectors" ++ seed))` where seed is specified on the command line (e.g. with `-s`) and by default it's just an empty string.

This has an advantage that concurrent tests won't interfere with each other.

When testing, the seed can be generated at random like [this](https://gist.github.com/earthgecko/3089509).

**Comment by inetic** [comment]
I have implemented what I described in my [previous comment](https://github.com/clostra/dcdn/issues/13#issuecomment-307746769) in [this commit](https://github.com/inetic/dcdn/commit/647ab32473ca060c4f4b5795f8dee636d3c4c892) (as part of PR #59).

@shalunov, let me know if you want me to continue with setting up public and private keys using command line before @ghazel merges his `ghazel` branch (seems like it might introduce conflicts).
