### ISSUE TITLE
address sanitizer

### ISSUE THREAD

**Issue by shalunov** [clostra/newnode#27]
We already have `-fsanitize=address`.

Should we use the output of the leak sanitizer?

Are there any ASAN_OPTIONS or LSAN_OPTIONS we should use?

Should we use `-fsanitize-address-use-after-scope`?

**Comment by inetic** [comment]
> Are there any ASAN_OPTIONS or LSAN_OPTIONS we should use?

According to [this](https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer) the `leak sanitizer` is enabled by default when `-fsanitizer=address` is used. Also, in that case we should only use `ASAN_OPTIONS` and not `LSAN_OPTIONS`.

[Here](https://github.com/google/sanitizers/wiki/AddressSanitizerFlags) is a list of available `address` sanitizer flags.

From this [FAQ](https://github.com/google/sanitizers/wiki/AddressSanitizer#faq):

> Q: Can I run AddressSanitizer with more aggressive diagnostics enabled?
> A: Yes! In particular you may want to enable
> `CFLAGS += -fsanitize-address-use-after-scope ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1`

It seems that the `-fsanitize-address-use-after-scope` has been [enabled by default](https://reviews.llvm.org/D31479) in llvm since March 30 2017. I was unable to find a way to tell which clang version this is going to start to have by default though.

Also, from the above link:

> because it is already very well tested, it's used in several projects already (LLVM automatically enables it when using -DLLVM_USE_SANITIZER=Address), it's low overhead and there are no known issues or incompatibilities.

So I suppose adding it won't hurt and will give us a few more checks on not-so-recent clang compilers.

Other flags which look interesting:
* `-fsanitize=memory` to enable [MemorySanitizer](https://github.com/google/sanitizers/wiki/MemorySanitizer) to detect the use of uninitialized memory. Note though that this one doesn't work with the AddressSanitizer, so it's _either-or_.
* `-fsanitize=undefined` to enable [UndefinedBehaviorSanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)

Just for reference, I also use the following env variables to see a nice backtraces:
```
export ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.8/bin/llvm-symbolizer
export MSAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.8/bin/llvm-symbolizer
```

**Comment by shalunov** [comment]
#30 is failing currently

**Comment by shalunov** [comment]
Also, the leak sanitizer is enabled, but I don't think anything fails if it finds leaks, and it's pretty unlikely we will even spot the leak sanitizer output in the build logs. By "use the output of the leak sanitizer" I meant failing the test if leaks are found.
