### ISSUE TITLE
investigate how to best use clang static analyzer

### ISSUE THREAD

**Issue by shalunov** [clostra/newnode#35]
It looks to me like we could add it to the Travis build. Is there a better way in terms of GitHub integration—a separate existing service, maybe with a bot?

**Comment by inetic** [comment]
As mentioned in #37, `clang-tidy` can do the job as well. But this issue is also asking where it's the best place to use it.

> It looks to me like we could add it to the Travis build.

Both clang-tidy and the static analyzer require compiler flags to be set the same way they are in the `build.sh` file. Thus in order to not have to sync the build options separately for compilation and separately for clang-tidy we have these options:

1. run clang-tidy inside build.sh
2. export build options into (e.g.) common.sh and use it in build.sh and a new script which runs clang-tidy
3. switch to cmake, which can export the build options using the `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` flag (see the `-p` option in [man clang-tidy](http://www.tin.org/bin/man.cgi?section=1&topic=clang-tidy-3.5))

**Comment by shalunov** [comment]
What about `.clang-tidy` to store options?

Currently, still produces benign warnings. If we silenced those, it could be run as a part of the Travis build, I suppose. How long does this take?

Thoughts on `clang-tidy` vs `scan-build`?

**Comment by inetic** [comment]
> What about `.clang-tidy` to store options?

I'm not sure `.clang-tidy` can contain compiler options, I'll check. But even if it could, adding them there would mean we have two versions of those options to keep in sync, one in `build.sh` and one in `.clang-tidy` and anyone modifying these options in one place would need to remember to modify them in the other place. I think this should be avoided.

> ... it could be run as a part of the Travis build ...

Yes, in Travis we'd just add a line such as

```
clang-tidy-3.8 -checks='*,-google-readability-casting,-llvm-include-order,-clang-analyzer-alpha.core.CastToStruct,-misc-unused-parameters,-google-readability-todo,-google-readability-braces-around-statements,-readability-braces-around-statements,-misc-macro-parentheses' *.c -- $CFLAGS $INCLUDE_DIRS
```

Where `$CFLAGS` and `$INCLUDE_DIRS` should be the same as those used in `build.sh`.

> How long does this take?

To run all checks on all C files at once takes less than 2 seconds. To run all checks on `dht.cpp` takes ~1.5 seconds as well.

> Thoughts on clang-tidy vs scan-build?

From [here](http://lists.llvm.org/pipermail/cfe-dev/2015-September/044966.html)

> "clang-tidy can be used as a frontend for the static analyzer checkers (they are called `clang-analyzer-<static-analyzer-checker-name>`)"

my understanding is that `clang-tidy` is the superior option.

**Comment by shalunov** [comment]
Too bad there isn't an integrated service for this. Closing in favor of #37.
