### ISSUE TITLE
coverage for injector_helper

### ISSUE THREAD

**Issue by shalunov** [clostra/newnode#44]
To better understand what we'll need to do to get good test coverage, let's start with injector helper.

**Comment by shalunov** [comment]
Is 58% the best we can have with integration tests? Does CI support IPv6? Why isn't the DHT joining code running? I think we could do a lot more.

**Comment by inetic** [comment]
Currently the tests don't use DHT. Instead `injector_helper` knows about `injector` through a [command line argument](https://github.com/clostra/dcdn/blob/e0d149ece37d45a88175d99a552db863a752d065/test.sh#L108).

I did it this way because:

1. The `injector` to which the `injector_helper` connects must be deterministic in tests.
2. Given that the `injector` is only supposed to connect to the _test_ `injector_helper` it very likely has not punched a hole through the NAT before the `injector_helper` attempts to connect.

(1) could potentially be solved by solving issue #13.

(2) is a bit trickier. I think Travis CI workers are not behind a NAT, not 100% sure though. In such case it would work there. For people behind a NAT though, the test would work only if they:

1. Have a NAT with support for [hairpinning](https://en.wikipedia.org/wiki/Hairpinning). Or
2. Explicitly open a UDP in their NAT. Or
3. We use something like uPnP. Or
4. We try to punch a hole ourselves.

I think I'd first try the fourth option...

> Does CI support IPv6?

I'll check, but does `libbtdht` even supports IPv6? I was under the impression it [doesn't](https://github.com/clostra/libbtdht/blob/51fc2e78547cceb0a88604f53696b0c686c2eb74/src/DhtImpl.cpp#L4666) (the string `nodes6` is nowhere to be found in `libbtdht` as described by [BEP0032](http://www.bittorrent.org/beps/bep_0032.html), also the [callback for finding nodes](https://github.com/clostra/libbtdht/blob/51fc2e78547cceb0a88604f53696b0c686c2eb74/src/DhtImpl.cpp#L4727) does not mentions type of the endpoints because only IPv4 is assumed).

**Comment by shalunov** [comment]
There's some untested IPv6 code. Do we need it? If yes, let's cover; if not, let's remove?

**Comment by inetic** [comment]
> There's some untested IPv6 code. Do we need it? If yes, let's cover; if not, let's remove?

AFAIK, that is really only [three lines here](https://codecov.io/gh/clostra/dcdn/src/e0d149ece37d45a88175d99a552db863a752d065/injector_helper.c#L107) and [here](https://codecov.io/gh/clostra/dcdn/src/e0d149ece37d45a88175d99a552db863a752d065/test_server.c#L106) (both are a copy/paste from [here](https://github.com/clostra/Libevent/blob/2ed537cdb54160ec747d085a541ce359247b7aec/sample/http-server.c#L395)). We don't necessarily NEED it as it seems `libbtdht` doesn't support IPv6. On the other hand it's something we WANT, so the other course of action would be to add support for it in `libbtdht`.

But even if we did add it, I haven't yet checked whether Travis supports IPv6, so we still may not be able to cover it with tests.

**Comment by inetic** [comment]
Just to have a complete picture: It seems the OSX Travis workers do have a support for IPv6, while Linux workers don't.

OSX:
```
# ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=b<RXCSUM,TXCSUM,VLAN_HWTAGGING>
	ether 00:50:56:9a:09:1b 
	inet6 fe80::401:bc6b:ccc3:99e0%en0 prefixlen 64 secured scopeid 0x4 
	inet 10.182.152.84 netmask 0xffffc000 broadcast 10.182.191.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (1000baseT <full-duplex>)
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::5c1f:7261:1086:5686%utun0 prefixlen 64 scopeid 0x5 
	nd6 options=201<PERFORMNUD,DAD>
```
Linux:
```
#ifconfig
eth0      Link encap:Ethernet  HWaddr 42:01:0a:0a:17:ca  
          inet addr:10.10.23.202  Bcast:10.10.23.202  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:11979 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8618 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:190239647 (190.2 MB)  TX bytes:830041 (830.0 KB)
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:32 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:18041 (18.0 KB)  TX bytes:18041 (18.0 KB)
```

Adding a support for IPv6 however would seem like a task in itself. Here are the courses of action I can see, @shalunov please let me know which one you prefer:

1. Leave the status quo (my preference for the MVP).
2. Remove the 6 lines mentioning IPv6.
3. Modify `injector.c`, `injector_helper.c` and `test_server.c` to use IPv6 when possible + leave `libbtdht` unchanged.
4. As above, but also modify `libbtdht` to support IPv6.
