### ISSUE TITLE
Does this SDK track me?

### ISSUE THREAD

**Issue by Kaned1as** [clostra/newnode#93]
Trying version `1.9.7` in Android Emulator x86_64 SDK 29.

1. Asks for location permission. There's no way to call `NewNode.init()` without it popping up.
2. Has bugsnag references in source code. There is no way to call `NewNode.init()` without initializing bugsnag reporting.

**Comment by Kaned1as** [comment]
Not stale

**Comment by AbsurdlySuspicious** [comment]
Android forces apps to acquire location permission and forces user to keep location enabled if app wants to do anything with wifi or bluetooth in background (or rather not through the system GUI), this is needed because user location can be possibly determined by tracking BSSIDs of nearby wifi APs. I believe it's related to this since this library also sets up mesh network between nearby devices. 

(I'm not affiliated with developer(s) of this project)

**Comment by Kaned1as** [comment]
@AbsurdlySuspicious thank you! This answers my p.1.

Still interested how bugsnag reporting works.

**Comment by Kaned1as** [comment]
Not stale

**Comment by ghazel** [comment]
The location permission comes from our use of Google Nearby, which is device-to-device technology. Scanning for nearby Bluetooth / WiFi devices could be used to infer location, but NewNode doesn't implement anything like that.

**Comment by ghazel** [comment]
You can call `NewNode.setRequestDiscoveryPermission(false)` before `NewNode.init()` to avoid that dialog prompt and disable device-to-device connectivity, but it is very much not recommended.

**Comment by Kaned1as** [comment]
@ghazel thanks for clarification
